# # This workflow uses actions that are not certified by GitHub.
# # They are provided by a third-party and are governed by
# # separate terms of service, privacy policy, and support
# # documentation.

# # GitHub recommends pinning actions to a commit SHA.
# # To get a newer version, you will need to update the SHA.
# # You can also reference a tag or branch, but the action may change without warning.

# name: Build and deploy a container to an Azure Web App

# env:
#   AZURE_WEBAPP_NAME: wonjun-board   # set this to your application's name

# on:
#   push:
#     branches:
#       - main

# permissions: write-all

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - uses: jsdaniell/create-json@v1.2.1
#         with:
#           name: "appsettings.json"
#           json: ${{ secrets.APPLICATION }}
#           dir: ./

#       - uses: microsoft/variable-substitution@v1
#         with:
#           files: 'appsettings.json'
#         env:
#           Jwt.Issuer: ${{ secrets.JWT_ISSUER }}
#           Jwt.Audience: ${{ secrets.JWT_AUDIENCE }}
#           Jwt.SecretKey: ${{ secrets.JWT_SECRET_KEY }}
#           ConnectionStrings.Redis: ${{ secrets.CONNECTION_REDIS }}
#           ConnectionStrings.MySQL: ${{ secrets.CONNECTION_MYSQL }}

#       - uses: actions/upload-artifact@v2
#         with:
#           name: application.json
#           path: ./appsettings.json

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Log in to GitHub container registry
#         uses: docker/login-action@v1.10.0
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.ACCESS_TOKEN }}

#       - name: Lowercase the repo name
#         run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

#       - name: Build and push container image to registry
#         uses: docker/build-push-action@v2
#         with:
#           context: ./ 
#           push: true
#           tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
#           file: ./Dockerfile

#   deploy:
#     runs-on: ubuntu-latest

#     needs: build

#     environment:
#       name: 'production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#       - name: Lowercase the repo name
#         run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

#       - name: Deploy to Azure Web App
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: ${{ env.AZURE_WEBAPP_NAME }}
#           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#           images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
